GET http://localhost:3000/health HTTP/1.1

// seller register
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
    "fullName": {
        "firstName": "dev",
        "lastName": "code"
    },
    "email": "anas.dev.code@gmail.com",
    "password": "user",
    "role": "user"
}

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "test_user@example.com",
    "password": "user"
}


Get http://localhost:3000/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NmYyZDg2Y2E0NmE2ZjY1YWU1MzhkMyIsImlhdCI6MTc2ODg5NTAyMCwiZXhwIjoxNzY4OTgxNDIwfQ.HgQq5P5aeCwqDD9IQyF1TIpRuOhiKswaF7i133p5cBE
