GET http://localhost:3000/health HTTP/1.1

// seller register
POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
    "fullName": {
        "firstName": "test",
        "lastName": "seller"
    },
    "email": "test_seller@example.com",
    "password": "seller",
    "role" : "seller"
}

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "test_seller@example.com",
    "password": "seller"
}


Get http://localhost:3000/users/me HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NmYyZDg2Y2E0NmE2ZjY1YWU1MzhkMyIsImlhdCI6MTc2ODg5NTAyMCwiZXhwIjoxNzY4OTgxNDIwfQ.HgQq5P5aeCwqDD9IQyF1TIpRuOhiKswaF7i133p5cBE
